---

title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

source: ./src
destination: ./_site

ENV: development

baseurl: "" 
url: ""


gems:
  - jekyll-assets


# Build settings
markdown:     kramdown
permalink:    pretty

exclude: [
  ".asset-cache",
  ".grunt",
  ".tmp",
  "_assets/vendor",
  "bower_components",
  "node_modules",
  "tmp"
]


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

assets:
  compress:
    css: true
  cache: .asset-cache
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/vendor
  features:
    liquid: true
    automatic_img_alt: false

