---

title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

source: ./src
destination: ./_site

ENV: development

baseurl: "" 
url: ""


# Build settings
markdown:     kramdown
permalink:    pretty

exclude: [
  ".asset-cache",
  ".grunt",
  ".tmp",
  "_assets/vendor",
  "bower_components",
  "node_modules",
  "tmp"
]
